### ISSUE TITLE
Code health and cleanup

### ISSUE THREAD

**Issue by evandbrown** [GoogleCloudPlatform/gcp-service-broker#207]
This issue exists to track opportunities to clean up the code base.

- [ ] Move from glide to dep for dependency management
- [x] `go fmt` everything
- [x] Updating CONTRIBUTING.md to include instructions for setting up Go environment
- [x] Remove `cmd/migrate/migrate` binary

**Comment by josephlewis42** [comment]
@evandbrown what do you think about migrating all the packages to use the fully qualified names so you can just `go build` after doing a `go get` rather than installing the extra binaries?

Also I'm sort of at a loss as to why PRs are done against the development branch rather than master, thoughts?
