### ISSUE TITLE
Support Cloud Profiler

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/gcp-service-broker#237]
We added Debugger support a while back. Would like to add Cloud Profiler support, and integrate w/ the buildpack.

**Comment by josephlewis42** [comment]
Hi Ray,

I'm not very familiar with the product, based on the site it looks like you only need the API to be enabled and to have a service account from one of the roles [here](https://cloud.google.com/profiler/docs/iam) similar to the other Stackdriver tools, is that correct or are there other resources that need to be provisioned in order to get the product working?

Cheers!
\- Joseph

**Comment by saturnism** [comment]
Correct. It'll be similar to the Service Broker's Cloud Debugger support (I wrote half of that :)

On the CF Buildpack side, we can then automatically detect profiler service is bound, and append the agent.

**Comment by josephlewis42** [comment]
Awesome!

I was able to get the basic code into a branch called stackdriver-profiler. I'm couldn't quickly find an official logo so it's using the generic Stackdriver one.

Feel free to try it out and look at the diff to see if there's something else in there you need: https://github.com/GoogleCloudPlatform/gcp-service-broker/pull/246/files
