### ISSUE TITLE
IAM Service Account/Credentials Integration with Credhub

### ISSUE THREAD

**Issue by tehkuhnz** [GoogleCloudPlatform/gcp-service-broker#247]
As a platform operator, I need IAM account and credential information that is created on "bind" service commands from the service broker to be stored inside of of credhub. PAS applications should then be able to broker to credhub and inject those credentials for that IAM role inside the app in a secure way. This will be ideal when trying to prevent credential exposure when doing a "cf env"

**Comment by josephlewis42** [comment]
Hi Nick, great suggestion!

It looks like there is some precedence for this with experimental work [Pivotal has done](https://github.com/cloudfoundry/secure-credentials-broker). To figure out how complex this will be, is your main threat model that the credential might be exposed through running a `cf env`?

Right now we also hold on to the credential in the backing SQL instance and I think masking that would be a little more tricky because we implicitly trust operators. I'm definitely not opposed to stopping credentials from being stored in the database, but it'll take some time to do in a correct and thoughtful way.

**Comment by josephlewis42** [comment]
There's more info about how to do Credhub integration here: https://github.com/cloudfoundry-incubator/credhub/blob/master/docs/secure-service-credentials.md#updated-service-workflow

Perhaps this would be a good place to collaborate with the Elastic folks, who are building out support for various secrets management providers in beats right now. We could not only gain support for Credhub, but also others like Vault.

**Comment by tehkuhnz** [comment]
The main concern is limiting the security exposure of a user dumping cf env. Tiles on pivotal network are starting to support "Enable Secure Service Instance Credentials". For instance the MySQL pivotal tile does this.  Having support for both credhub and vault I think would be extremely valuable.

**Comment by josephlewis42** [comment]
Closing because the GCP Service Broker no longer supports installation via Tile.
