### ISSUE TITLE
Support changing plan of CloudSQL services

### ISSUE THREAD

**Issue by martinpfeifer** [GoogleCloudPlatform/gcp-service-broker#354]
Hi,

when i create a CloudSQL service
```
cf create-service google-cloudsql-mysql mysql-db-f1-micro my-mysql -c '{"region":"europe-west4","authorized_networks":"0.0.0.0/0"}'
```
and then try to change the used plan
```
cf update-service my-mysql -p mysql-db-g1-small
```
i get an error that changing the plan is not supported.
```
Updating service instance test as admin...
FAILED
Server error, status code: 400, error code: 110004, message: The service does not support changing plans.
```
GCP does allow to resize CloudSQL instances. Are there any plans to implement this feature in the service broker?

Best Regards

**Comment by josephlewis42** [comment]
Hi Martin,

Right now we don't support upgrading any plans right now. Upgrading can be tricky because some changes are irreversible and others will trigger the entire resource to be destroyed and re-created losing all data in the process.

If you need to upgrade/downgrade an existing instance, that's okay to do in the console, the instance should still be able to be bound to/destroyed through the service-broker.

We have an upcoming feature of the broker that might make upgrades doable, so I'll keep this issue updated while that rolls out as part of 4.2.0. Essentially, we're going to allow the broker to use Terraform behind the scenes, and TF does a pretty good job of telling you when a resource can be upgraded vs will be forced to be re-created so we can probably add a new field to our services that will let the TF broker determine if they can be upgraded or not.

Cheers!
\- Joseph

**Comment by martinpfeifer** [comment]
Hi Joseph,

thanks for your reply. I'm looking forward to test the TF feature :)

Best regards
