### ISSUE TITLE
kubectl plugin

### ISSUE THREAD

**Issue by craigdbarber** [GoogleCloudPlatform/gcp-service-broker#427]
@josephlewis42 and I briefly discussed the idea of implementing a kubectl plugin for the SB, which would provide analogs of many of the current `cf` based interactions with the SB. This would be a good step towards making use of the gcp-service-broker in k8s natively a first-class user story. I wanted to kick off the conversation here so we could brainstorm.

**Comment by josephlewis42** [comment]
I'm interested in getting your ideas about what areas you think we could improve on because this isn't a space I've worked a lot in. For background, the way we'd probably approach this today would be to use the [Kubernetes Service Catalog](https://svc-cat.io/) to use the broker from Kubernetes and a helm chart to deploy the broker.

The Kubernetes service catalog maps services and plans from the broker into custom resources in K8s. It has a CLI that's cf-ish and allows you to provision, bind, and unbind, and destroy resources. Additional items would need to be built onto svcat, or we could build something custom.

An interesting idea I've had would be to remove the broker from the equation entirely and instead replace it with a simpler service that provides CRDs directly to k8s for a given brokerpak. Essentially, bundle a brokerpak with the binary in a docker image and it becomes a provider wiping out a lot of the cruft the broker has today.

**Comment by craigatgoogle** [comment]
That is a very neat idea, it would allow you to break free from the vestiges of of the CF use-case. Very worthwhile exploring.

**Comment by craigatgoogle** [comment]
Also I agree, brokerpak has the potential to stand on its own as a utility that is employed by both the traditional SB as well as the CRD based SB k8s service.

**Comment by craigatgoogle** [comment]
Just a quick follow up, I think long term having a separate CRD based k8s service is definitely a worthy goal. That said, I wonder as a first iteration into the k8s space, if it would be more expedient to integrate the SB as is with the service catalog, just so we can make something available for users as soon as possible. Also, this would gives us an opportunity to get some experience/context in this space which we can use to better design a longer term solution. Let me know what you think.

**Comment by PK85** [comment]
Hi, exposing your gcp-broker application in the k8s Service Catalog world is more or less:
- create a helm chart 
  - your application will be represented as a k8s Deployment and Service, rbac etc
  - add a ClusterServiceBroker CR (Service Catalog domain) that point to k8s Service URL + auth

And that's it, service classes exposed via your broker are available in the Service Catalog.
Cheers, PK

**Comment by josephlewis42** [comment]
Hi @PK85,

We have a helm chart for installing the broker into K8s for use with the service catalog, but it's currently in the develop branch. We are currently using that chart with http://github.com/google/kf but I think that's the only place.

Cheers!
\- Joseph
