### ISSUE TITLE
Support service sharing

### ISSUE THREAD

**Issue by shinmyung0** [GoogleCloudPlatform/gcp-service-broker#459]
We are using the PCF Tile for the GCP Service Broker and we were wondering if there were plans to support service sharing outlined here?

https://docs.pivotal.io/pivotalcf/2-4/services/enable-sharing.html

**Comment by josephlewis42** [comment]
Hi @shinmyung0,

Officially, we don't recommend sharing because it's a non-standard feature of brokers and can lead to privilege escalation issues if you're not careful.

We do support it, but you have to set the `GSB_COMPATIBILITY_ENABLE_CF_SHARING` environment variable to `true`--you might need to make CF re-poll the catalog to pick up the change afterwards. If you're using opsman you can check the `enable-cf-sharing` flag in the tile configuration.

Here's more info about the other flags and options we support: https://github.com/GoogleCloudPlatform/gcp-service-broker/blob/master/docs/customization.md#compatibility

Cheers!
\- Joseph

**Comment by shinmyung0** [comment]
Thank you will close this~
