### ISSUE TITLE
Allow configuration of the GCP Service Broker App to multiple instances

### ISSUE THREAD

**Issue by shinmyung0** [GoogleCloudPlatform/gcp-service-broker#461]
I am using the GCP Service Broker PCF Tile v4.2.2 . I am noticing that the resource configuration does not allow me to configure more than 1 service broker instance. Is there a reason why there is only a single instance of this? Or is there a way for us to deploy more instances of the broker?

**Comment by josephlewis42** [comment]
Hi @shinmyung0,

Right now (to the best of my knowledge) Pivotal doesn't support configuring multiple instances of a single tile. However, the broker can be installed as a regular `cf` application using `cf push` into a space and registered as a space broker.

You will have to manually configure some environment variables for accessing a MySQL database (these can be shared across multiple brokers, but each broker MUST have its own `DB_NAME`) and a `ROOT_SERVICE_ACCOUNT_JSON` associated with the GCP project.

The full set of configuration options can be found in the `/docs/configuration.md` file for your specific implementation. There's also a docker script in the root of the project if it would help you to use the broker as a Docker image instead of a regular CF application.

**Comment by shinmyung0** [comment]
Hmm I meant more that the service broker itself only runs as a single app instance within cf? I was wondering if there are any limitations to have say 3 instances of the service broker app running? I don't mean differently configured necessarily, just HA

**Comment by josephlewis42** [comment]
That's a great question. You should be able to run more than one version of the broker just fine as long as you're accessing it through the cloud controller or Kubernetes service catalog with one caveat.

If you installed and are using any brokerpaks (a way to extend the broker with Terraform), those must be executed on a single node unless there's a way to guarantee the same cloud controller instance will always hit the same back-end node.
