### ISSUE TITLE
missing documentation wrt to deploy to CF with custom brokerpak

### ISSUE THREAD

**Issue by poblin-orange** [GoogleCloudPlatform/gcp-service-broker#520]
I successfully managed to deploy gc-service-broker to Cloudfoundry OSS.
Also, i did package a custom brokerpak for testing.
However, i dont see any instructions/documentation to let the gc-service-broker cf app load my custom brokerpak ?

**Comment by dominikmueller** [comment]
I can't help with documentation about deploying it on OSS Cloudfoundry, but you might be able to get some hints about which environment variables you need to set in your manifest by looking at the `tile.yml` (at least that's how I interpret it):

https://github.com/GoogleCloudPlatform/gcp-service-broker/blob/b4c1f1794841d9d6000dddd354caf707b27ea468/tile.yml#L506

The name of the form defines the necessary environment variable. So the upper reference would result in a variable named "GSB_BROKERPAK_SOURCES".

https://github.com/GoogleCloudPlatform/gcp-service-broker/blob/b4c1f1794841d9d6000dddd354caf707b27ea468/tile.yml#L510-L546

The properties section for that form defines what kind of JSON key-value pairs you need to provide through that environment variable.

An example would be:
```yaml
GSB_BROKERPAK_SOURCES: {"uri": "gs://foo/bar.brokerpak?checksum=md5:3063a2c62e82ef8614eee6745a7b6b59", "service_prefix": "experimental-", "config": "{}", "notes": "An example for configuring brokerpaks"}
```

There are plenty of other forms that might help to configure the GCP service broker to your needs.

Nevertheless, I also think that there is some documentation missing. But since the brokerpak feature still is in development there hopefully is more to come :)

**Comment by poblin-orange** [comment]
@dominikmueller  thks! Il try this.
